// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.7.0
//
// <auto-generated>
//
// Generated from file `Morceau.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.example.sy.myapplication.TP;

public interface MorceauPrx extends com.zeroc.Ice.ObjectPrx
{
    default void ajouter(son s)
    {
        ajouter(s, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void ajouter(son s, java.util.Map<String, String> context)
    {
        _iceI_ajouterAsync(s, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> ajouterAsync(son s)
    {
        return _iceI_ajouterAsync(s, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> ajouterAsync(son s, java.util.Map<String, String> context)
    {
        return _iceI_ajouterAsync(s, context, false);
    }

    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_ajouterAsync(son iceP_s, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "ajouter", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeValue(iceP_s);
                     ostr.writePendingValues();
                 }, null);
        return f;
    }

    default void supprimer(son s)
    {
        supprimer(s, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void supprimer(son s, java.util.Map<String, String> context)
    {
        _iceI_supprimerAsync(s, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> supprimerAsync(son s)
    {
        return _iceI_supprimerAsync(s, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> supprimerAsync(son s, java.util.Map<String, String> context)
    {
        return _iceI_supprimerAsync(s, context, false);
    }

    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_supprimerAsync(son iceP_s, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "supprimer", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeValue(iceP_s);
                     ostr.writePendingValues();
                 }, null);
        return f;
    }

    default son findByTitle(String name)
    {
        return findByTitle(name, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default son findByTitle(String name, java.util.Map<String, String> context)
    {
        return _iceI_findByTitleAsync(name, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<son> findByTitleAsync(String name)
    {
        return _iceI_findByTitleAsync(name, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<son> findByTitleAsync(String name, java.util.Map<String, String> context)
    {
        return _iceI_findByTitleAsync(name, context, false);
    }

    default com.zeroc.IceInternal.OutgoingAsync<son> _iceI_findByTitleAsync(String iceP_name, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<son> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "findByTitle", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_name);
                 }, istr -> {
                     final com.zeroc.IceInternal.Holder<son> ret = new com.zeroc.IceInternal.Holder<>();
                     istr.readValue(v -> ret.value = v, son.class);
                     istr.readPendingValues();
                     return ret.value;
                 });
        return f;
    }

    default son[] findByAlbum(String name)
    {
        return findByAlbum(name, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default son[] findByAlbum(String name, java.util.Map<String, String> context)
    {
        return _iceI_findByAlbumAsync(name, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<son[]> findByAlbumAsync(String name)
    {
        return _iceI_findByAlbumAsync(name, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<son[]> findByAlbumAsync(String name, java.util.Map<String, String> context)
    {
        return _iceI_findByAlbumAsync(name, context, false);
    }

    default com.zeroc.IceInternal.OutgoingAsync<son[]> _iceI_findByAlbumAsync(String iceP_name, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<son[]> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "findByAlbum", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_name);
                 }, istr -> {
                     son[] ret;
                     ret = sonsHelper.read(istr);
                     istr.readPendingValues();
                     return ret;
                 });
        return f;
    }

    default son[] findByAuthor(String name)
    {
        return findByAuthor(name, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default son[] findByAuthor(String name, java.util.Map<String, String> context)
    {
        return _iceI_findByAuthorAsync(name, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<son[]> findByAuthorAsync(String name)
    {
        return _iceI_findByAuthorAsync(name, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<son[]> findByAuthorAsync(String name, java.util.Map<String, String> context)
    {
        return _iceI_findByAuthorAsync(name, context, false);
    }

    default com.zeroc.IceInternal.OutgoingAsync<son[]> _iceI_findByAuthorAsync(String iceP_name, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<son[]> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "findByAuthor", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_name);
                 }, istr -> {
                     son[] ret;
                     ret = sonsHelper.read(istr);
                     istr.readPendingValues();
                     return ret;
                 });
        return f;
    }

    default son[] findByGenre(String genre)
    {
        return findByGenre(genre, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default son[] findByGenre(String genre, java.util.Map<String, String> context)
    {
        return _iceI_findByGenreAsync(genre, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<son[]> findByGenreAsync(String genre)
    {
        return _iceI_findByGenreAsync(genre, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<son[]> findByGenreAsync(String genre, java.util.Map<String, String> context)
    {
        return _iceI_findByGenreAsync(genre, context, false);
    }

    default com.zeroc.IceInternal.OutgoingAsync<son[]> _iceI_findByGenreAsync(String iceP_genre, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<son[]> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "findByGenre", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_genre);
                 }, istr -> {
                     son[] ret;
                     ret = sonsHelper.read(istr);
                     istr.readPendingValues();
                     return ret;
                 });
        return f;
    }

    default son findById(int id)
    {
        return findById(id, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default son findById(int id, java.util.Map<String, String> context)
    {
        return _iceI_findByIdAsync(id, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<son> findByIdAsync(int id)
    {
        return _iceI_findByIdAsync(id, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<son> findByIdAsync(int id, java.util.Map<String, String> context)
    {
        return _iceI_findByIdAsync(id, context, false);
    }

    default com.zeroc.IceInternal.OutgoingAsync<son> _iceI_findByIdAsync(int iceP_id, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<son> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "findById", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeInt(iceP_id);
                 }, istr -> {
                     final com.zeroc.IceInternal.Holder<son> ret = new com.zeroc.IceInternal.Holder<>();
                     istr.readValue(v -> ret.value = v, son.class);
                     istr.readPendingValues();
                     return ret.value;
                 });
        return f;
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static MorceauPrx checkedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, ice_staticId(), MorceauPrx.class, _MorceauPrxI.class);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static MorceauPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, context, ice_staticId(), MorceauPrx.class, _MorceauPrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static MorceauPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, ice_staticId(), MorceauPrx.class, _MorceauPrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static MorceauPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, context, ice_staticId(), MorceauPrx.class, _MorceauPrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @return A proxy for this type.
     **/
    static MorceauPrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, MorceauPrx.class, _MorceauPrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type.
     **/
    static MorceauPrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, facet, MorceauPrx.class, _MorceauPrxI.class);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the per-proxy context.
     * @param newContext The context for the new proxy.
     * @return A proxy with the specified per-proxy context.
     **/
    @Override
    default MorceauPrx ice_context(java.util.Map<String, String> newContext)
    {
        return (MorceauPrx)_ice_context(newContext);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the adapter ID.
     * @param newAdapterId The adapter ID for the new proxy.
     * @return A proxy with the specified adapter ID.
     **/
    @Override
    default MorceauPrx ice_adapterId(String newAdapterId)
    {
        return (MorceauPrx)_ice_adapterId(newAdapterId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoints.
     * @param newEndpoints The endpoints for the new proxy.
     * @return A proxy with the specified endpoints.
     **/
    @Override
    default MorceauPrx ice_endpoints(com.zeroc.Ice.Endpoint[] newEndpoints)
    {
        return (MorceauPrx)_ice_endpoints(newEndpoints);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator cache timeout.
     * @param newTimeout The new locator cache timeout (in seconds).
     * @return A proxy with the specified locator cache timeout.
     **/
    @Override
    default MorceauPrx ice_locatorCacheTimeout(int newTimeout)
    {
        return (MorceauPrx)_ice_locatorCacheTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the invocation timeout.
     * @param newTimeout The new invocation timeout (in seconds).
     * @return A proxy with the specified invocation timeout.
     **/
    @Override
    default MorceauPrx ice_invocationTimeout(int newTimeout)
    {
        return (MorceauPrx)_ice_invocationTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for connection caching.
     * @param newCache <code>true</code> if the new proxy should cache connections; <code>false</code> otherwise.
     * @return A proxy with the specified caching policy.
     **/
    @Override
    default MorceauPrx ice_connectionCached(boolean newCache)
    {
        return (MorceauPrx)_ice_connectionCached(newCache);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoint selection policy.
     * @param newType The new endpoint selection policy.
     * @return A proxy with the specified endpoint selection policy.
     **/
    @Override
    default MorceauPrx ice_endpointSelection(com.zeroc.Ice.EndpointSelectionType newType)
    {
        return (MorceauPrx)_ice_endpointSelection(newType);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for how it selects endpoints.
     * @param b If <code>b</code> is <code>true</code>, only endpoints that use a secure transport are
     * used by the new proxy. If <code>b</code> is false, the returned proxy uses both secure and
     * insecure endpoints.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default MorceauPrx ice_secure(boolean b)
    {
        return (MorceauPrx)_ice_secure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the encoding used to marshal parameters.
     * @param e The encoding version to use to marshal request parameters.
     * @return A proxy with the specified encoding version.
     **/
    @Override
    default MorceauPrx ice_encodingVersion(com.zeroc.Ice.EncodingVersion e)
    {
        return (MorceauPrx)_ice_encodingVersion(e);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its endpoint selection policy.
     * @param b If <code>b</code> is <code>true</code>, the new proxy will use secure endpoints for invocations
     * and only use insecure endpoints if an invocation cannot be made via secure endpoints. If <code>b</code> is
     * <code>false</code>, the proxy prefers insecure endpoints to secure ones.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default MorceauPrx ice_preferSecure(boolean b)
    {
        return (MorceauPrx)_ice_preferSecure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the router.
     * @param router The router for the new proxy.
     * @return A proxy with the specified router.
     **/
    @Override
    default MorceauPrx ice_router(com.zeroc.Ice.RouterPrx router)
    {
        return (MorceauPrx)_ice_router(router);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator.
     * @param locator The locator for the new proxy.
     * @return A proxy with the specified locator.
     **/
    @Override
    default MorceauPrx ice_locator(com.zeroc.Ice.LocatorPrx locator)
    {
        return (MorceauPrx)_ice_locator(locator);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for collocation optimization.
     * @param b <code>true</code> if the new proxy enables collocation optimization; <code>false</code> otherwise.
     * @return A proxy with the specified collocation optimization.
     **/
    @Override
    default MorceauPrx ice_collocationOptimized(boolean b)
    {
        return (MorceauPrx)_ice_collocationOptimized(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses twoway invocations.
     * @return A proxy that uses twoway invocations.
     **/
    @Override
    default MorceauPrx ice_twoway()
    {
        return (MorceauPrx)_ice_twoway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses oneway invocations.
     * @return A proxy that uses oneway invocations.
     **/
    @Override
    default MorceauPrx ice_oneway()
    {
        return (MorceauPrx)_ice_oneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch oneway invocations.
     * @return A proxy that uses batch oneway invocations.
     **/
    @Override
    default MorceauPrx ice_batchOneway()
    {
        return (MorceauPrx)_ice_batchOneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses datagram invocations.
     * @return A proxy that uses datagram invocations.
     **/
    @Override
    default MorceauPrx ice_datagram()
    {
        return (MorceauPrx)_ice_datagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch datagram invocations.
     * @return A proxy that uses batch datagram invocations.
     **/
    @Override
    default MorceauPrx ice_batchDatagram()
    {
        return (MorceauPrx)_ice_batchDatagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, except for compression.
     * @param co <code>true</code> enables compression for the new proxy; <code>false</code> disables compression.
     * @return A proxy with the specified compression setting.
     **/
    @Override
    default MorceauPrx ice_compress(boolean co)
    {
        return (MorceauPrx)_ice_compress(co);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection timeout setting.
     * @param t The connection timeout for the proxy in milliseconds.
     * @return A proxy with the specified timeout.
     **/
    @Override
    default MorceauPrx ice_timeout(int t)
    {
        return (MorceauPrx)_ice_timeout(t);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection ID.
     * @param connectionId The connection ID for the new proxy. An empty string removes the connection ID.
     * @return A proxy with the specified connection ID.
     **/
    @Override
    default MorceauPrx ice_connectionId(String connectionId)
    {
        return (MorceauPrx)_ice_connectionId(connectionId);
    }

    static String ice_staticId()
    {
        return "::TP::Morceau";
    }
}
