// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.7.0
//
// <auto-generated>
//
// Generated from file `Morceau.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.example.sy.myapplication.TP;

public class son extends com.zeroc.Ice.Value
{
    public son()
    {
        this.album = "";
        this.genre = "";
        this.title = "";
        this.date = "";
        this.author = "";
        this.path = "";
    }

    public son(String album, String genre, String title, String date, String author, String path, int id)
    {
        this.album = album;
        this.genre = genre;
        this.title = title;
        this.date = date;
        this.author = author;
        this.path = path;
        this.id = id;
    }

    public String album;

    public String genre;

    public String title;

    public String date;

    public String author;

    public String path;

    public int id;

    public son clone()
    {
        return (son)super.clone();
    }

    public static String ice_staticId()
    {
        return "::TP::son";
    }

    @Override
    public String ice_id()
    {
        return ice_staticId();
    }

    public static final long serialVersionUID = 7881988902575155661L;

    @Override
    protected void _iceWriteImpl(com.zeroc.Ice.OutputStream ostr_)
    {
        ostr_.startSlice(ice_staticId(), -1, true);
        ostr_.writeString(album);
        ostr_.writeString(genre);
        ostr_.writeString(title);
        ostr_.writeString(date);
        ostr_.writeString(author);
        ostr_.writeString(path);
        ostr_.writeInt(id);
        ostr_.endSlice();
    }

    @Override
    protected void _iceReadImpl(com.zeroc.Ice.InputStream istr_)
    {
        istr_.startSlice();
        album = istr_.readString();
        genre = istr_.readString();
        title = istr_.readString();
        date = istr_.readString();
        author = istr_.readString();
        path = istr_.readString();
        id = istr_.readInt();
        istr_.endSlice();
    }
}
