// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.7.0
//
// <auto-generated>
//
// Generated from file `PlayerMp3.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.example.sy.myapplication.PlayerMp3;

public interface PlayerPrx extends com.zeroc.Ice.ObjectPrx
{
    default boolean addSon(String name, String singer, String author, String album, String path)
    {
        return addSon(name, singer, author, album, path, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default boolean addSon(String name, String singer, String author, String album, String path, java.util.Map<String, String> context)
    {
        return _iceI_addSonAsync(name, singer, author, album, path, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<java.lang.Boolean> addSonAsync(String name, String singer, String author, String album, String path)
    {
        return _iceI_addSonAsync(name, singer, author, album, path, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.lang.Boolean> addSonAsync(String name, String singer, String author, String album, String path, java.util.Map<String, String> context)
    {
        return _iceI_addSonAsync(name, singer, author, album, path, context, false);
    }

    default com.zeroc.IceInternal.OutgoingAsync<java.lang.Boolean> _iceI_addSonAsync(String iceP_name, String iceP_singer, String iceP_author, String iceP_album, String iceP_path, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.Boolean> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "addSon", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_name);
                     ostr.writeString(iceP_singer);
                     ostr.writeString(iceP_author);
                     ostr.writeString(iceP_album);
                     ostr.writeString(iceP_path);
                 }, istr -> {
                     boolean ret;
                     ret = istr.readBool();
                     return ret;
                 });
        return f;
    }

    default boolean deleteSon(String name)
    {
        return deleteSon(name, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default boolean deleteSon(String name, java.util.Map<String, String> context)
    {
        return _iceI_deleteSonAsync(name, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<java.lang.Boolean> deleteSonAsync(String name)
    {
        return _iceI_deleteSonAsync(name, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.lang.Boolean> deleteSonAsync(String name, java.util.Map<String, String> context)
    {
        return _iceI_deleteSonAsync(name, context, false);
    }

    default com.zeroc.IceInternal.OutgoingAsync<java.lang.Boolean> _iceI_deleteSonAsync(String iceP_name, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.Boolean> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "deleteSon", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_name);
                 }, istr -> {
                     boolean ret;
                     ret = istr.readBool();
                     return ret;
                 });
        return f;
    }

    default Son searchSon(String name)
    {
        return searchSon(name, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default Son searchSon(String name, java.util.Map<String, String> context)
    {
        return _iceI_searchSonAsync(name, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Son> searchSonAsync(String name)
    {
        return _iceI_searchSonAsync(name, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Son> searchSonAsync(String name, java.util.Map<String, String> context)
    {
        return _iceI_searchSonAsync(name, context, false);
    }

    default com.zeroc.IceInternal.OutgoingAsync<Son> _iceI_searchSonAsync(String iceP_name, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Son> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "searchSon", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_name);
                 }, istr -> {
                     final com.zeroc.IceInternal.Holder<Son> ret = new com.zeroc.IceInternal.Holder<>();
                     istr.readValue(v -> ret.value = v, Son.class);
                     istr.readPendingValues();
                     return ret.value;
                 });
        return f;
    }

    default Son[] getSons()
    {
        return getSons(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default Son[] getSons(java.util.Map<String, String> context)
    {
        return _iceI_getSonsAsync(context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Son[]> getSonsAsync()
    {
        return _iceI_getSonsAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Son[]> getSonsAsync(java.util.Map<String, String> context)
    {
        return _iceI_getSonsAsync(context, false);
    }

    default com.zeroc.IceInternal.OutgoingAsync<Son[]> _iceI_getSonsAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Son[]> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getSons", null, sync, null);
        f.invoke(true, context, null, null, istr -> {
                     Son[] ret;
                     ret = SonListHelper.read(istr);
                     istr.readPendingValues();
                     return ret;
                 });
        return f;
    }

    default void MafactoryMethode(String[] s)
    {
        MafactoryMethode(s, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void MafactoryMethode(String[] s, java.util.Map<String, String> context)
    {
        _iceI_MafactoryMethodeAsync(s, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> MafactoryMethodeAsync(String[] s)
    {
        return _iceI_MafactoryMethodeAsync(s, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> MafactoryMethodeAsync(String[] s, java.util.Map<String, String> context)
    {
        return _iceI_MafactoryMethodeAsync(s, context, false);
    }

    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_MafactoryMethodeAsync(String[] iceP_s, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "MafactoryMethode", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeStringSeq(iceP_s);
                 }, null);
        return f;
    }

    default boolean play(String name)
    {
        return play(name, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default boolean play(String name, java.util.Map<String, String> context)
    {
        return _iceI_playAsync(name, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<java.lang.Boolean> playAsync(String name)
    {
        return _iceI_playAsync(name, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.lang.Boolean> playAsync(String name, java.util.Map<String, String> context)
    {
        return _iceI_playAsync(name, context, false);
    }

    default com.zeroc.IceInternal.OutgoingAsync<java.lang.Boolean> _iceI_playAsync(String iceP_name, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.Boolean> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "play", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_name);
                 }, istr -> {
                     boolean ret;
                     ret = istr.readBool();
                     return ret;
                 });
        return f;
    }

    default void stop()
    {
        stop(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void stop(java.util.Map<String, String> context)
    {
        _iceI_stopAsync(context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> stopAsync()
    {
        return _iceI_stopAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> stopAsync(java.util.Map<String, String> context)
    {
        return _iceI_stopAsync(context, false);
    }

    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_stopAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "stop", null, sync, null);
        f.invoke(false, context, null, null, null);
        return f;
    }

    default void pause()
    {
        pause(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void pause(java.util.Map<String, String> context)
    {
        _iceI_pauseAsync(context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> pauseAsync()
    {
        return _iceI_pauseAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> pauseAsync(java.util.Map<String, String> context)
    {
        return _iceI_pauseAsync(context, false);
    }

    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_pauseAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "pause", null, sync, null);
        f.invoke(false, context, null, null, null);
        return f;
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static PlayerPrx checkedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, ice_staticId(), PlayerPrx.class, _PlayerPrxI.class);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static PlayerPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, context, ice_staticId(), PlayerPrx.class, _PlayerPrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static PlayerPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, ice_staticId(), PlayerPrx.class, _PlayerPrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static PlayerPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, context, ice_staticId(), PlayerPrx.class, _PlayerPrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @return A proxy for this type.
     **/
    static PlayerPrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, PlayerPrx.class, _PlayerPrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type.
     **/
    static PlayerPrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, facet, PlayerPrx.class, _PlayerPrxI.class);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the per-proxy context.
     * @param newContext The context for the new proxy.
     * @return A proxy with the specified per-proxy context.
     **/
    @Override
    default PlayerPrx ice_context(java.util.Map<String, String> newContext)
    {
        return (PlayerPrx)_ice_context(newContext);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the adapter ID.
     * @param newAdapterId The adapter ID for the new proxy.
     * @return A proxy with the specified adapter ID.
     **/
    @Override
    default PlayerPrx ice_adapterId(String newAdapterId)
    {
        return (PlayerPrx)_ice_adapterId(newAdapterId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoints.
     * @param newEndpoints The endpoints for the new proxy.
     * @return A proxy with the specified endpoints.
     **/
    @Override
    default PlayerPrx ice_endpoints(com.zeroc.Ice.Endpoint[] newEndpoints)
    {
        return (PlayerPrx)_ice_endpoints(newEndpoints);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator cache timeout.
     * @param newTimeout The new locator cache timeout (in seconds).
     * @return A proxy with the specified locator cache timeout.
     **/
    @Override
    default PlayerPrx ice_locatorCacheTimeout(int newTimeout)
    {
        return (PlayerPrx)_ice_locatorCacheTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the invocation timeout.
     * @param newTimeout The new invocation timeout (in seconds).
     * @return A proxy with the specified invocation timeout.
     **/
    @Override
    default PlayerPrx ice_invocationTimeout(int newTimeout)
    {
        return (PlayerPrx)_ice_invocationTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for connection caching.
     * @param newCache <code>true</code> if the new proxy should cache connections; <code>false</code> otherwise.
     * @return A proxy with the specified caching policy.
     **/
    @Override
    default PlayerPrx ice_connectionCached(boolean newCache)
    {
        return (PlayerPrx)_ice_connectionCached(newCache);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoint selection policy.
     * @param newType The new endpoint selection policy.
     * @return A proxy with the specified endpoint selection policy.
     **/
    @Override
    default PlayerPrx ice_endpointSelection(com.zeroc.Ice.EndpointSelectionType newType)
    {
        return (PlayerPrx)_ice_endpointSelection(newType);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for how it selects endpoints.
     * @param b If <code>b</code> is <code>true</code>, only endpoints that use a secure transport are
     * used by the new proxy. If <code>b</code> is false, the returned proxy uses both secure and
     * insecure endpoints.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default PlayerPrx ice_secure(boolean b)
    {
        return (PlayerPrx)_ice_secure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the encoding used to marshal parameters.
     * @param e The encoding version to use to marshal request parameters.
     * @return A proxy with the specified encoding version.
     **/
    @Override
    default PlayerPrx ice_encodingVersion(com.zeroc.Ice.EncodingVersion e)
    {
        return (PlayerPrx)_ice_encodingVersion(e);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its endpoint selection policy.
     * @param b If <code>b</code> is <code>true</code>, the new proxy will use secure endpoints for invocations
     * and only use insecure endpoints if an invocation cannot be made via secure endpoints. If <code>b</code> is
     * <code>false</code>, the proxy prefers insecure endpoints to secure ones.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default PlayerPrx ice_preferSecure(boolean b)
    {
        return (PlayerPrx)_ice_preferSecure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the router.
     * @param router The router for the new proxy.
     * @return A proxy with the specified router.
     **/
    @Override
    default PlayerPrx ice_router(com.zeroc.Ice.RouterPrx router)
    {
        return (PlayerPrx)_ice_router(router);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator.
     * @param locator The locator for the new proxy.
     * @return A proxy with the specified locator.
     **/
    @Override
    default PlayerPrx ice_locator(com.zeroc.Ice.LocatorPrx locator)
    {
        return (PlayerPrx)_ice_locator(locator);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for collocation optimization.
     * @param b <code>true</code> if the new proxy enables collocation optimization; <code>false</code> otherwise.
     * @return A proxy with the specified collocation optimization.
     **/
    @Override
    default PlayerPrx ice_collocationOptimized(boolean b)
    {
        return (PlayerPrx)_ice_collocationOptimized(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses twoway invocations.
     * @return A proxy that uses twoway invocations.
     **/
    @Override
    default PlayerPrx ice_twoway()
    {
        return (PlayerPrx)_ice_twoway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses oneway invocations.
     * @return A proxy that uses oneway invocations.
     **/
    @Override
    default PlayerPrx ice_oneway()
    {
        return (PlayerPrx)_ice_oneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch oneway invocations.
     * @return A proxy that uses batch oneway invocations.
     **/
    @Override
    default PlayerPrx ice_batchOneway()
    {
        return (PlayerPrx)_ice_batchOneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses datagram invocations.
     * @return A proxy that uses datagram invocations.
     **/
    @Override
    default PlayerPrx ice_datagram()
    {
        return (PlayerPrx)_ice_datagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch datagram invocations.
     * @return A proxy that uses batch datagram invocations.
     **/
    @Override
    default PlayerPrx ice_batchDatagram()
    {
        return (PlayerPrx)_ice_batchDatagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, except for compression.
     * @param co <code>true</code> enables compression for the new proxy; <code>false</code> disables compression.
     * @return A proxy with the specified compression setting.
     **/
    @Override
    default PlayerPrx ice_compress(boolean co)
    {
        return (PlayerPrx)_ice_compress(co);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection timeout setting.
     * @param t The connection timeout for the proxy in milliseconds.
     * @return A proxy with the specified timeout.
     **/
    @Override
    default PlayerPrx ice_timeout(int t)
    {
        return (PlayerPrx)_ice_timeout(t);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection ID.
     * @param connectionId The connection ID for the new proxy. An empty string removes the connection ID.
     * @return A proxy with the specified connection ID.
     **/
    @Override
    default PlayerPrx ice_connectionId(String connectionId)
    {
        return (PlayerPrx)_ice_connectionId(connectionId);
    }

    static String ice_staticId()
    {
        return "::PlayerMp3::Player";
    }
}
