// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.7.0
//
// <auto-generated>
//
// Generated from file `PlayerMp3.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.example.sy.myapplication.PlayerMp3;

public class Son extends com.zeroc.Ice.Value
{
    public Son()
    {
        this.name = "";
        this.singer = "";
        this.author = "";
        this.album = "";
        this.path = "";
    }

    public Son(String name, String singer, String author, String album, String path)
    {
        this.name = name;
        this.singer = singer;
        this.author = author;
        this.album = album;
        this.path = path;
    }

    public String name;

    public String singer;

    public String author;

    public String album;

    public String path;

    public Son clone()
    {
        return (Son)super.clone();
    }

    public static String ice_staticId()
    {
        return "::PlayerMp3::Son";
    }

    @Override
    public String ice_id()
    {
        return ice_staticId();
    }

    public static final long serialVersionUID = 7273285691887317045L;

    @Override
    protected void _iceWriteImpl(com.zeroc.Ice.OutputStream ostr_)
    {
        ostr_.startSlice(ice_staticId(), -1, true);
        ostr_.writeString(name);
        ostr_.writeString(singer);
        ostr_.writeString(author);
        ostr_.writeString(album);
        ostr_.writeString(path);
        ostr_.endSlice();
    }

    @Override
    protected void _iceReadImpl(com.zeroc.Ice.InputStream istr_)
    {
        istr_.startSlice();
        name = istr_.readString();
        singer = istr_.readString();
        author = istr_.readString();
        album = istr_.readString();
        path = istr_.readString();
        istr_.endSlice();
    }
}
